### PR TITLE
add sshkeyadd

### PR DESCRIPTION
**Pull request by xyb994**
https://github.com/ole-vi/treehouse-builder/issues/75

### CODE REVIEW

**Comment by dogi** [comment]
```
/bin/sh: 1: /usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh: Permission denied

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 126,
  signal: null,
  cmd: '/usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== nemo@mela' }
```

**Review by dogi — APPROVED** [review]

**Review by dogi — COMMENTED** [review]
please add the README.md stuff ;)

**Comment by i5o** [comment]
Testing :)

**Comment by i5o** [comment]
Perhaps we need `mkdir -p /root/.ssh /home/pi/.ssh` -- just in case?
```
root@raspberrypi:/home/pi# npm install @pirateship/cli@0.2.7-sshkeyadd2
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ @pirateship/cli@0.2.7-sshkeyadd2
added 3 packages in 7.388s
root@raspberrypi:/home/pi# cat .ssh/authorized_keys
cat: .ssh/authorized_keys: No such file or directory
root@raspberrypi:/home/pi# cat /root/.ssh/authorized_keys
cat: /root/.ssh/authorized_keys: No such file or directory
root@raspberrypi:/home/pi# npm install @pirateship/cli@0.2.7-sshkeyadd2 -g
/usr/bin/pirateship -> /usr/lib/node_modules/@pirateship/cli/cli.js
+ @pirateship/cli@0.2.7-sshkeyadd2
added 3 packages in 4.61s
root@raspberrypi:/home/pi# pirateship sshkeyadd ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNtR1gq8JF+y+sAgUV+4wfF9OTXkaNVpDVWv4JU8GPNaVJP1dMQ1GcYRrI877z/QsZk9UOu08bSUU8ggengygyz7RJPDV3+HYTjIJXO9FmfGA/1FrE1aoEPfTkNhqq70PbPwJCPQZf/T2zNIGKeMLJ/E/I+Jysg6SDlHk6zWIWbTeBFKQsNj9fQTsAGoSThGHcxEB/eQJ0tLBUb8MhGJSLtExSbhT8Dw63pYAb0BtzNnGesaCQTxAycxBk8XOQP0nO6rjyRPF9hjfYFslk1aeq29HIeLrC+tX0Vql59M/2CRx8inmYvZJetjf79TBymlclj/Zulum9KJ6nCGwXuIuv ignacio@ignacio-laptop
{ Error: Command failed: /usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh ssh-rsa
/usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh: line 3: /home/pi/.ssh/authorized_keys: No such file or directory
chmod: cannot access '/home/pi/.ssh/authorized_keys': No such file or directory
/usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh: line 6: /root/.ssh/authorized_keys: No such file or directory
chmod: cannot access '/root/.ssh/authorized_keys': No such file or directory

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/@pirateship/cli/lib/sshkeyadd.sh ssh-rsa' }
root@raspberrypi:/home/pi#
```

**Comment by i5o** [comment]
```
pi@raspberrypi:~ $ cat .ssh/
cat: .ssh/: Permission denied
pi@raspberrypi:~ $
```

**Comment by i5o** [comment]
We need to add chown too

```
pi@raspberrypi:~ $ cat .ssh/
cat: .ssh/: Permission denied
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# chown pi:pi /home/pi/.ssh
root@raspberrypi:/home/pi# exit
pi@raspberrypi:~ $ cat .ssh/
cat: .ssh/: Is a directory
pi@raspberrypi:~ $ cat .ssh/authorized_keys
cat: .ssh/authorized_keys: Permission denied
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# chown -R pi:pi /home/pi/.ssh
root@raspberrypi:/home/pi# exit
pi@raspberrypi:~ $ cat .ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNtR1gq8JF+y+sAgUV+4wfF9OTXkaNVpDVWv4JU8GPNaVJP1dMQ1GcYRrI877z/QsZk9UOu08bSUU8ggengygyz7RJPDV3+HYTjIJXO9FmfGA/1FrE1aoEPfTkNhqq70PbPwJCPQZf/T2zNIGKeMLJ/E/I+Jysg6SDlHk6zWIWbTeBFKQsNj9fQTsAGoSThGHcxEB/eQJ0tLBUb8MhGJSLtExSbhT8Dw63pYAb0BtzNnGesaCQTxAycxBk8XOQP0nO6rjyRPF9hjfYFslk1aeq29HIeLrC+tX0Vql59M/2CRx8inmYvZJetjf79TBymlclj/Zulum9KJ6nCGwXuIuv ignacio@ignacio-laptop
pi@raspberrypi:~ $
```

I will add it on the next commit

**Review by dogi — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
